# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog_img.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_img(object):
    def setupUi(self, Dialog_img):
        Dialog_img.setObjectName("Dialog_img")
        Dialog_img.resize(453, 338)
        self.gridLayoutWidget = QtWidgets.QWidget(Dialog_img)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(80, 60, 301, 152))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.radioButton_select_putCircle = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButton_select_putCircle.setObjectName("radioButton_select_putCircle")
        self.gridLayout.addWidget(self.radioButton_select_putCircle, 3, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.radioButton_high_density = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButton_high_density.setObjectName("radioButton_high_density")
        self.gridLayout.addWidget(self.radioButton_high_density, 1, 1, 1, 1)
        self.radioButton_custom = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButton_custom.setObjectName("radioButton_custom")
        self.gridLayout.addWidget(self.radioButton_custom, 4, 1, 1, 1)
        self.radioButton_select_sidewayRect = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButton_select_sidewayRect.setObjectName("radioButton_select_sidewayRect")
        self.gridLayout.addWidget(self.radioButton_select_sidewayRect, 2, 0, 1, 1)
        self.radioButton_select_putRect = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButton_select_putRect.setCheckable(True)
        self.radioButton_select_putRect.setChecked(False)
        self.radioButton_select_putRect.setObjectName("radioButton_select_putRect")
        self.gridLayout.addWidget(self.radioButton_select_putRect, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.radioButton_mid_density = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButton_mid_density.setObjectName("radioButton_mid_density")
        self.gridLayout.addWidget(self.radioButton_mid_density, 2, 1, 1, 1)
        self.radioButton_low_density = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButton_low_density.setChecked(False)
        self.radioButton_low_density.setObjectName("radioButton_low_density")
        self.gridLayout.addWidget(self.radioButton_low_density, 3, 1, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit.setEnabled(False)
        self.lineEdit.setInputMask("")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 5, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(Dialog_img)
        self.pushButton.setGeometry(QtCore.QRect(280, 250, 93, 28))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Dialog_img)
        QtCore.QMetaObject.connectSlotsByName(Dialog_img)

    def retranslateUi(self, Dialog_img):
        _translate = QtCore.QCoreApplication.translate
        Dialog_img.setWindowTitle(_translate("Dialog_img", "Dialog for img imput"))
        self.radioButton_select_putCircle.setText(_translate("Dialog_img", "正放圆形"))
        self.label_2.setText(_translate("Dialog_img", "请选择图形类别:"))
        self.radioButton_high_density.setText(_translate("Dialog_img", "高"))
        self.radioButton_custom.setText(_translate("Dialog_img", "自定义"))
        self.radioButton_select_sidewayRect.setText(_translate("Dialog_img", "斜放矩形"))
        self.radioButton_select_putRect.setText(_translate("Dialog_img", "正放矩形"))
        self.label.setText(_translate("Dialog_img", "请选择网格密度:"))
        self.radioButton_mid_density.setText(_translate("Dialog_img", "中"))
        self.radioButton_low_density.setText(_translate("Dialog_img", "低"))
        self.lineEdit.setPlaceholderText(_translate("Dialog_img", "请输入2-50之间的整数"))
        self.pushButton.setText(_translate("Dialog_img", "确定"))
