# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog_paint_dxf.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_paint_dxf(object):
    def setupUi(self, Dialog_paint_dxf):
        Dialog_paint_dxf.setObjectName("Dialog_paint_dxf")
        Dialog_paint_dxf.resize(410, 290)
        self.label = QtWidgets.QLabel(Dialog_paint_dxf)
        self.label.setGeometry(QtCore.QRect(90, 40, 121, 16))
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(Dialog_paint_dxf)
        self.pushButton.setGeometry(QtCore.QRect(260, 250, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.layoutWidget = QtWidgets.QWidget(Dialog_paint_dxf)
        self.layoutWidget.setGeometry(QtCore.QRect(100, 90, 173, 130))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.radioButton_high_density = QtWidgets.QRadioButton(self.layoutWidget)
        self.radioButton_high_density.setChecked(False)
        self.radioButton_high_density.setObjectName("radioButton_high_density")
        self.verticalLayout.addWidget(self.radioButton_high_density)
        self.radioButton_mid_density = QtWidgets.QRadioButton(self.layoutWidget)
        self.radioButton_mid_density.setObjectName("radioButton_mid_density")
        self.verticalLayout.addWidget(self.radioButton_mid_density)
        self.radioButton_low_density = QtWidgets.QRadioButton(self.layoutWidget)
        self.radioButton_low_density.setChecked(True)
        self.radioButton_low_density.setObjectName("radioButton_low_density")
        self.verticalLayout.addWidget(self.radioButton_low_density)
        self.radioButton_custom = QtWidgets.QRadioButton(self.layoutWidget)
        self.radioButton_custom.setObjectName("radioButton_custom")
        self.verticalLayout.addWidget(self.radioButton_custom)
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit.setEnabled(True)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)

        self.retranslateUi(Dialog_paint_dxf)
        QtCore.QMetaObject.connectSlotsByName(Dialog_paint_dxf)

    def retranslateUi(self, Dialog_paint_dxf):
        _translate = QtCore.QCoreApplication.translate
        Dialog_paint_dxf.setWindowTitle(_translate("Dialog_paint_dxf", "Dialog for paint and dxf"))
        self.label.setText(_translate("Dialog_paint_dxf", "请选择网格密度："))
        self.pushButton.setText(_translate("Dialog_paint_dxf", "确定"))
        self.radioButton_high_density.setText(_translate("Dialog_paint_dxf", "高"))
        self.radioButton_mid_density.setText(_translate("Dialog_paint_dxf", "中"))
        self.radioButton_low_density.setText(_translate("Dialog_paint_dxf", "低"))
        self.radioButton_custom.setText(_translate("Dialog_paint_dxf", "自定义"))
